name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup GitHub Credentials
        run: |
          git config user.name ${GITHUB_ACTOR}
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
      - name: Publish site
        run: |
          ./bin/deploy.sh